name: pyls
summary: Python Language Server
description: |
  A Python implementation of the Language Server Protocol.

  See https://github.com/palantir/python-language-server for details.
license: MIT
confinement: strict
grade: stable
base: core20
architectures:
  - build-on: amd64
adopt-info: pyls

apps:
  pyls:
    command: bin/pyls
    plugs:
      - home
      - network-bind
  isort:
    command: bin/isort
    plugs:
      - home
  mypy:
    command: bin/mypy
    plugs:
      - home    
  pyflakes:
    command: bin/pyflakes
    plugs:
      - home
  pylint:
    command: bin/pylint
    plugs:
      - home
  yapf:
    command: bin/yapf
    plugs:
      - home

parts:
  pyls:
    plugin: python
    source: .
    source-type: git
    python-packages:
      - python-language-server[all]
      - pyls-black
      - pyls-isort
      - pyls-mypy
    prime:
      - bin
      - lib
      - pyvenv.cfg
    override-build: |
      set -e
      snapcraftctl build
      PYLS_VERSION="$(pip show pip | awk '/^Version/ { print $2}')"
      GIT_HASH="$(git --work-tree "$SNAPCRAFT_PROJECT_DIR" rev-parse --short HEAD)"
      snapcraftctl set-version "${PYLS_VERSION}-snap.${GIT_HASH}"
      python3 -m compileall -q .
